---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-preview
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        owner: acm-uic
        repo: IaC
        labels:
          - preview
        requeueAfterSeconds: 500
  template:
    metadata:
      name: 'pr-{{branch}}-{{number}}'
      namespace: argocd
    spec:
      source:
        repoUrl: 'git@github.com:acm-uic/IaC.git'
        targetRevision: '{{head_sha}}'
        path: kubernetes/argocd/maid-cafe-stacks/appsets
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{branch}}-{{number}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
