---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-preview
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - pullRequest:
        github:
          owner: acm-uic
          repo: IaC
          labels:
            - ':wheel_of_dharma: k8s'
        requeueAfterSeconds: 60
  template:
    metadata:
      name: 'pr-{{.branch}}-{{.number}}'
      namespace: argocd
    spec:
      source:
        repoURL: 'git@github.com:acm-uic/IaC.git'
        targetRevision: '{{.head_sha}}'
        path: kubernetes/argocd/maid-cafe-stacks/appsets
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{.branch}}-{{.number}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
