---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: plausible
  name: clickhouse-config
data:
  users-config: |
    <clickhouse>
        <profiles>
            <default>
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
            </default>
        </profiles>
    </clickhouse>
  config: |
    <clickhouse>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>

        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
        <session_log remove="remove"/>
        <part_log remove="remove"/>
    </clickhouse>
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clickhouse-pvc
  namespace: plausible
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
  namespace: plausible
  labels:
    app.kubernetes.io/name: clickhouse
spec:
  serviceName: "clickhouse"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: clickhouse
  template:
    metadata:
      labels:
        app.kubernetes.io/name: clickhouse
    spec:
      serviceAccountName: plausible
      containers:
        - name: clickhouse
          image: docker.io/clickhouse/clickhouse-server:23.3.7.5-alpine
          ports:
            - containerPort: 8123
              name: http
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/clickhouse
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/config.d/logging.xml
              subPath: config
              readOnly: true
            - name: clickhouse-config
              mountPath: /etc/clickhouse-server/users.d/logging.xml
              subPath: users-config
              readOnly: true
          env:
            - name: CLICKHOUSE_DB
              value: plausible
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: clickhouse-pvc
        - name: clickhouse-config
          configMap:
            name: clickhouse-config
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: plausible
  labels:
    app.kubernetes.io/name: clickhouse
spec:
  ports:
    - port: 8123
      name: http
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clickhouse
