---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: plausible
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: mayastor-3
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: plausible
  labels:
    app.kubernetes.io/name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/tls-secret: "plausible-vault-cert"
        vault.hashicorp.com/role: "plausible"
        vault.hashicorp.com/agent-inject-secret-config: "kv/plausible"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{- with secret "kv/plausible" -}}
            export POSTGRES_PASSWORD="{{ .Data.data.POSTGRES_PLAUSIBLE_PASSWORD }}"
          {{- end }}
      labels:
        app.kubernetes.io/name: postgres
    spec:
      serviceAccountName: plausible
      containers:
        - name: postgres
          image: postgres:14-alpine
          command:
            - "/bin/sh"
            - "-c"
            # disable huge pages to fix "Bus error (core dumped)"
            # https://github.com/kubernetes/kubernetes/issues/71233#issuecomment-447472125
            - "sed -i 's/#huge_pages = try/huge_pages = off/g' /usr/local/share/postgresql/postgresql.conf.sample && \
              source /vault/secrets/config && \
              docker-entrypoint.sh postgres"
          env:
            - name: POSTGRES_DB
              value: plausible
            - name: POSTGRES_USER
              value: plausible
          ports:
            - containerPort: 5432
              name: postgresdb
          volumeMounts:
            - name: pv-data
              mountPath: /var/lib/postgresql/data
              subPath: data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: plausible
  labels:
    app.kubernetes.io/name: postgres
spec:
  ports:
    - port: 5432
      name: postgresdb
  type: ClusterIP
  selector:
    app.kubernetes.io/name: postgres
