---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: plausible
  name: smtp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: smtp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: smtp
    spec:
      containers:
        - name: smtp
          image: bytemark/smtp
          ports:
            - containerPort: 25
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: plausible
  name: smtp
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: smtp
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
