---
apiVersion: v1
kind: Namespace
metadata:
  name: marketplace
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: marketplace
  namespace: marketplace
  annotations:
    external-dns.alpha.kubernetes.io/target: app.acmuic.org
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`marketplace.acmuic.org`)
    services:
    - kind: Service
      name: marketplace
      namespace: marketplace
      passHostHeader: true
      port: 3000
      responseForwarding:
        flushInterval: 1ms
      scheme: http
      strategy: RoundRobin
      weight: 10
  - kind: Rule
    match: "Host(`marketplace.acmuic.org`) && (PathPrefix(`/api`) || PathPrefix(`/_`))"
    services:
    - kind: Service
      name: pocketbase
      namespace: marketplace
      passHostHeader: true
      port: 80
      responseForwarding:
        flushInterval: 1ms
      scheme: http
      strategy: RoundRobin
      weight: 10
  tls:
    secretName: marketplace-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: marketplace-tls
spec:
  dnsNames:
    - marketplace.acmuic.org
  secretName: marketplace-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
