---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'git@github.com:acm-uic/IaC.git'
    targetRevision: 'HEAD'
    path: 'kubernetes/argocd/stacks/common/cert-manager'
    include: 'cert-manager.crds.yml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io'
    chart: 'cert-manager'
    targetRevision: 'v1.12.2'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
