
[sssd]
domains = acmuic.org
config_file_version = 2
services = nss, pam

[domain/acmuic.org]
default_shell = /bin/bash
krb5_store_password_if_offline = True
cache_credentials = True
krb5_realm = ACMUIC.ORG
realmd_tags = manages-system joined-with-adcli
id_provider = ad
ad_server = addc1.acmuic.org,addc2.acmuic.org
fallback_homedir = /shared/home/%u
ad_domain = acmuic.org
use_fully_qualified_names = False
ldap_id_mapping = True
access_provider = ad
enumerate = True
dns_discovery_domain = acmuic.org
auth_provider = krb5
krb5_canonicalize = True
[nss]
override_homedir = /shared/home/%u




