---
- name: Pi Router Setup
  hosts: all
  tasks:
    - name: Install Kea
      become: true
      apt:
        name: kea
        state: present
        update_cache: true

    - name: Install NVIM
      become: true
      apt:
        name: neovim
        state: present
        update_cache: true

    - name: Install Nginx
      become: true
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Install network detection script
      become: true
      template:
        src: network-detect.sh.j2
        dest: /usr/local/bin/network-detect.sh
        mode: 0755
      when: install_network_detection

    - name: Install network detection service
      become: true
      copy:
        src: files/network-detect.service
        dest: /etc/systemd/system/network-detect.service
        mode: 0644
      when: install_network_detection

    - name: Enable network detection service
      become: true
      systemd:
        name: network-detect
        enabled: true
        daemon_reload: true
      when: install_network_detection

    - name: Disable auto startup of Kea DHCP6 server
      become: true
      systemd:
        name: kea-dhcp6-server
        enabled: false
      when: install_network_detection

    - name: Enable auto startup of Kea DHCP4 server
      become: true
      systemd:
        name: kea-dhcp4-server
        enabled: true

    - name: Download netboot.xyx.efi and place it in the nginx web root
      become: true
      get_url:
        url: https://boot.netboot.xyz/ipxe/netboot.xyz-snp.efi
        dest: /var/www/html/netboot.xyz.efi
        mode: 0644

    - name: Set Kea DHCP6 server configuration
      become: true
      template:
        src: kea-dhcp6.conf.j2
        dest: /etc/kea/kea-dhcp6.conf
        mode: 0644

    - name: Set Kea DHCP4 server configuration
      become: true
      template:
        src: kea-dhcp4.conf.j2
        dest: /etc/kea/kea-dhcp4.conf
        mode: 0644

    - name: Install RADVD service
      become: true
      apt:
        name: radvd
        state: present
        update_cache: true

    - name: Disable RADVD service
      become: true
      systemd:
        name: radvd
        enabled: false
      when: install_network_detection

    - name: Configure RADVD service
      become: true
      template:
        src: radvd.conf.j2
        dest: /etc/radvd.conf
        mode: 0644

    - name: Enable IPv6 forwarding
      become: true
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        state: present

    - name: Install tftpd-hpa
      become: true
      apt:
        name: tftpd-hpa
        state: present
        update_cache: true

    - name: Download ipxe.efi for UEFI clients
      become: true
      get_url:
        url: https://boot.ipxe.org/ipxe.efi
        dest: /srv/tftp/ipxe.efi
        mode: 0755

    - name: Download undionly.kpxe for BIOS clients
      become: true
      get_url:
        url: https://boot.ipxe.org/undionly.kpxe
        dest: /srv/tftp/undionly.kpxe
        mode: 0755

    - name: Copy iPXE chainloading config - HTTP
      become: true
      template:
        src: ipxe.conf.j2
        dest: /var/www/html/ipxe.conf
        mode: 0644

    - name: Copy iPXE menu - HTTP
      become: true
      template:
        src: menu.ipxe.j2
        dest: /var/www/html/menu.ipxe
        mode: 0644

    - name: Copy boot.cfg variables - HTTP
      become: true
      template:
        src: boot.cfg.j2
        dest: /var/www/html/boot.cfg
        mode: 0644

    - name: Copy netinfo.ipxe menu - HTTP
      become: true
      template:
        src: netinfo.ipxe.j2
        dest: /var/www/html/netinfo.ipxe
        mode: 0644

    - name: Download Proxmox ISO netboot prepper script
      get_url:
        url: https://raw.githubusercontent.com/morph027/pve-iso-2-pxe/refs/heads/master/pve-iso-2-pxe.sh
        dest: /home/acmadmin/pve-iso-2-pxe.sh
        mode: 0755

    - name: Download Proxmox ISO
      get_url:
        url: https://enterprise.proxmox.com/iso/proxmox-ve_8.2-2.iso
        dest: /home/acmadmin/proxmox-ve_8.2-2.iso
        mode: 0644

    - name: Install Prepper dependencies - cpio
      become: true
      apt:
        name: cpio
        state: present
        update_cache: true

    - name: Install Prepper dependencies - file
      become: true
      apt:
        name: file
        state: present
        update_cache: true

    - name: Install Prepper dependencies - zstd
      become: true
      apt:
        name: zstd
        state: present
        update_cache: true

    - name: Install Prepper dependencies - gzip
      become: true
      apt:
        name: gzip
        state: present
        update_cache: true

    - name: Install Prepper dependencies - genisoimage
      become: true
      apt:
        name: genisoimage
        state: present
        update_cache: true

    - name: Download TrueNAS Scale ISO
      become: true
      get_url:
        url: https://download.sys.truenas.net/TrueNAS-SCALE-Dragonfish/24.04.2.3/TrueNAS-SCALE-24.04.2.3.iso
        dest: /var/www/html/TrueNAS-SCALE-24.04.2.3.iso
        mode: 0644

    - name: Install index page for web server
      become: true
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: 0644
