---
- name: Pi Router Setup
  hosts: all
  tasks:
    - name: Install Kea
      become: true
      apt:
        name: kea
        state: present
        update_cache: true

    - name: Install NVIM
      become: true
      apt:
        name: neovim
        state: present
        update_cache: true

    - name: Install Nginx
      become: true
      apt:
        name: nginx
        state: present
        update_cache: true

    - name: Install network detection script
      become: true
      template:
        src: network-detect.sh.j2
        dest: /usr/local/bin/network-detect.sh
        mode: 0755
      when: install_network_detection

    - name: Install network detection service
      become: true
      copy:
        src: files/network-detect.service
        dest: /etc/systemd/system/network-detect.service
        mode: 0644
      when: install_network_detection

    - name: Enable network detection service
      become: true
      systemd:
        name: network-detect
        enabled: true
        daemon_reload: true
      when: install_network_detection

    - name: Disable auto startup of Kea DHCP6 server
      become: true
      systemd:
        name: kea-dhcp6-server
        enabled: false
      when: install_network_detection

    - name: Enable auto startup of Kea DHCP4 server
      become: true
      systemd:
        name: kea-dhcp4-server
        enabled: true

    - name: Download netboot.xyx.efi and place it in the nginx web root
      become: true
      get_url:
        url: https://boot.netboot.xyz/ipxe/netboot.xyz-snp.efi
        dest: /var/www/html/netboot.xyz.efi
        mode: 0755

    - name: Set Kea DHCP6 server configuration
      become: true
      template:
        src: kea-dhcp6.conf.j2
        dest: /etc/kea/kea-dhcp6.conf
        mode: 0644

    - name: Set Kea DHCP4 server configuration
      become: true
      template:
        src: kea-dhcp4.conf.j2
        dest: /etc/kea/kea-dhcp4.conf
        mode: 0644

    - name: Install RADVD service
      become: true
      apt:
        name: radvd
        state: present
        update_cache: true

    - name: Disable RADVD service
      become: true
      systemd:
        name: radvd
        enabled: false
      when: install_network_detection

    - name: Configure RADVD service
      become: true
      template:
        src: radvd.conf.j2
        dest: /etc/radvd.conf
        mode: 0644

    - name: Enable IPv6 forwarding
      become: true
      sysctl:
        name: net.ipv6.conf.all.forwarding
        value: 1
        state: present

