---
provider: azure
serviceAccount:
  name: externaldns
podAnnotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'externaldns'
  vault.hashicorp.com/agent-inject-secret-azure.json: 'kv/externaldns/service_account'
  vault.hashicorp.com/ca-cert: "/run/secrets/kubernetes.io/serviceaccount/ca.crt"
  vault.hashicorp.com/agent-inject-template-azure.json: |
    {{- with secret "kv/externaldns/service_account" -}}
    {
      "tenantId" : "{{ .Data.data.tenantId }}",
      "subscriptionId" : "{{ .Data.data.subscriptionId }}",
      "resourceGroup" : "{{ .Data.data.resourceGroup }}",
      "aadClientId" : "{{ .Data.data.aadClientId }}",
      "aadClientSecret" : "{{ .Data.data.aadClientSecret }}"
    }
    {{- end }}
extraArgs: ["--azure-config-file=/vault/secrets/azure.json"]
