# systemd provides a thing called myhostname for nsswitch to manage resolving
# current system hostname/IP when hostnames are changing and such.
# this is cause applications use getaddrinfo and expect it to always work for 
# eg. current hostname. I don't want to go thru the trouble of adding each nodes
# IP and hostname in /etc/hosts, so I wanna keep it around.
# However, systemd will cough up any ipv6 address when asked about current node,
# even if it is link-local or unroutable.
# This breaks MPICH Hydra which expects to call getaddrinfo and use that IP to
# reach across nodes in an allocation.
# 500iq name resolution mess from 60 years ago still haunts us.
# Disable IPv6 link-local addresses for now.
# net.ipv6.conf.all.addr_gen_mode = 1
# net.ipv6.conf.default.addr_gen_mode = 1

# that doesnt work either, disable ipv6 fuck it
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1