[Unit]
# Check key gen script exists
AssertPathExists=/usr/nerv/mungekey.sh
# and is executable
AssertFileIsExecutable=/usr/nerv/mungekey.sh

[Service]
# since this is a drop-in override, we need to clear the existing values.
# otherwise, everything is additive/appended.
ExecStartPre=
# just in case
ExecStartPre=+chmod +x /usr/nerv/mungekey.sh
# this will create munge.key from sops if it doesnt already exist.
# The leading + makes it run as root and not as munge user,
# which is needed so sops can access the ssh private key.
ExecStartPre=+/usr/bin/bash /usr/nerv/mungekey.sh
ExecStart=
# munge is a pedantic piece of shit jesus
ExecStart=/usr/sbin/munged --syslog --force --key-file=/var/etc/munge/munge.key
