---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bmes-tls
spec:
  dnsNames:
    - convergehealth.cc
  secretName: bmes-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
