---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # The following labels are required to allow MetalLB to use
    # additional networking protocols for L2 advertisement.
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: metallb-system
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: maid-cafe-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.25.9.31-172.25.9.254
  - fd2b:9a1d:cafe:9::7d2-fd2b:9a1d:cafe:9::1000
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: maid-cafe-bgp
  namespace: metallb-system
spec:
  ipAddressPools:
    - maid-cafe-pool
  aggregationLength: 32
