kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mariadb-pvc-data
  namespace: mariadb
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
