---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sparkhacks-tls
spec:
  dnsNames:
    - sparkhacksatuic.com
  secretName: sparkhacks-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
