---
all:
  children:
    proxmox_hosts:
      hosts:
        boba:
          ansible_host: 172.25.1.3
          ansible_user: root
        chai:
          ansible_host: 172.25.1.4
          ansible_user: root
        coffee:
          ansible_host: 172.25.1.2
          ansible_user: root
        matcha:
          ansible_host: 172.25.1.5
          ansible_user: root
        earlgrey:
          ansible_host: 172.25.1.6
          ansible_user: root
      vars:
        ansible_python_interpreter: /usr/bin/python3
