kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nextcloud-pvc
  namespace: nextcloud
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500Gi