[Unit]
ConditionHost=misato*
# Check key gen script exists
AssertPathExists=/usr/nerv/mariadbkey.sh
# and is executable
AssertFileIsExecutable=/usr/nerv/mariadbkey.sh

[Service]
ExecStartPost=+/usr/bin/bash /usr/nerv/mariadbkey.sh