---
- name: Setup Longyan as the door strike controller
  hosts: all
  vars:
    runner_username: acmrunner
    doorkeeper_controller_git_url: 'https://github.com/lugatuic/doorkeeper-controller.git'
    discord_bot_git_url: 'https://github.com/lugatuic/doorbot-discord.git'
    install_doorkeeper_controller: true
    install_doorbot_discord: false
  tasks:
    - name: Create acmrunner group
      become: true
      ansible.builtin.group:
        name: "{{ runner_username }}"
        state: present
    - name: Create acmrunner user
      become: true
      ansible.builtin.user:
        name: "{{ runner_username }}"
        groups: "{{ runner_username }},gpio"
        shell: /usr/bin/tmux
        home: "/opt/{{ runner_username }}"
        comment: Service user used to run the doorkeeper controllers
    - name: Setup autologin
      include_role:
        name: autologin
    - name: Install tmux
      become: true
      ansible.builtin.package:
        name: tmux
        state: present
    - name: Install git
      become: true
      ansible.builtin.package:
        name: git
        state: present
    - name: Setup doorkeeper_controller
      include_role:
        name: doorkeeper_install
      when: install_doorkeeper_controller
    - name: Install Discord bot code
      include_role:
        name: doorbot_install
      when: install_doorbot_discord

