kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-pvc-logs
  namespace: gitlab
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
