---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iac
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
    - path: kubernetes/argocd/maid-cafe-stacks/appsets
      repoURL: 'git@github.com:acm-uic/IaC.git' 
      targetRevision: 'main'
    - path: kubernetes/argocd/maid-cafe-stacks/manifests
      repoURL: 'git@github.com:acm-uic/IaC.git' 
      targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
