d  /var/etc 0755 root root - -
d  /var/etc/ssh 0755 root root - -
#C  /var/etc/machine-id - - - - /etc/machine-id
#L+ /etc/machine-id - - - - /var/etc/machine-id
L+ /etc/hostname - - - - /var/etc/hostname
L+ /etc/ostree/auth.json - - - - /var/secrets/auth.json
L+ /usr/libexec/openssh/sshd-keygen - - - - /dev/zero