d /var/spool/slurmd 0740 slurm slurm - -
d /var/spool/slurmctld 0740 slurm slurm - -
d /tmp/var/spool/slurmd 0740 slurm slurm - -
d /tmp/var/spool/slurmctld 0740 slurm slurm - -
d  /var/etc/slurm 0600 slurm slurm - -
L+ /etc/slurm/slurmdbd.conf 0600 root root - /var/etc/slurm/slurmdbd.conf