---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arc
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: arc-systems
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      targetRevision: 0.14.2
      chart: gha-runner-scale-set-controller
      helm:
        valueFiles:
          - $values/kubernetes/argocd/stacks/arc/values.yml
    - path: kubernetes/argocd/stacks/arc
      repoURL: 'https://github.com/acm-uic/IaC.git'
      targetRevision: HEAD
      ref: values
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
