---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # The following labels are required to allow hostpath-provisioner
    # to use additional networking and host-level volume operations.
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: hostpath-provisioner
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hostpath-provisioner
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: hostpath-provisioner
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.rimusz.net'
    targetRevision: 0.2.13
    chart: hostpath-provisioner
    helm:
      parameters:
        - name: storageClass.defaultClass
          value: 'false'
        - name: nodeHostPath
          value: '/var/hostpath-provisioner'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
