---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marketplace
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: marketplace
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://acm.cs.uic.edu/helm'
      targetRevision: 0.1.3
      chart: 'marketplace'
      path: 'helm'
      helm:
        valueFiles:
          - $values/kubernetes/argocd/stacks/marketplace/values.yml
    - path: kubernetes/argocd/stacks/marketplace
      repoURL: 'git@github.com:acm-uic/IaC.git'
      targetRevision: feature/marketplace
      ref: values
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: sigweb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

