---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    # The following labels are required to allow Mayastor to use
    # additional networking and host-level volume operations.
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
  name: mayastor
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: mayastor
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://openebs.github.io/mayastor-extensions'
    targetRevision: 2.2.0
    chart: mayastor
    helm:
      parameters:
        - name: etcd.persistence.storageClass
          value: nfs-csi
        - name: loki-stack.loki.persistence.storageClassName
          value: nfs-csi
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-k8s-04
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  node: k8s-04
  disks: ["/dev/vdb"]
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-k8s-05
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  node: k8s-05
  disks: ["/dev/vdb"]
---
apiVersion: "openebs.io/v1alpha1"
kind: DiskPool
metadata:
  name: pool-k8s-06
  namespace: mayastor
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  node: k8s-06
  disks: ["/dev/vdb"]
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  # This storage class is replicated across 3 nodes
  name: mayastor-3
  annotations:
    argocd.argoproj.io/sync-wave: "3"
parameters:
  ioTimeout: "30"
  protocol: nvmf
  repl: "3"
provisioner: io.openebs.csi-mayastor
