---
apiVersion: v1
kind: Namespace
metadata:
  name: mayastor
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayastor
spec:
  destination:
    name: ''
    namespace: mayastor
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://openebs.github.io/mayastor-extensions'
    targetRevision: 2.2.0
    chart: mayastor
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
