---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-crd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/acm-uic/IaC.git'
    targetRevision: HEAD
    path: kubernetes/argocd/stacks/traefik
    directory:
      include: '*.crds.yaml'
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: traefik
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://traefik.github.io/charts'
      targetRevision: 41.5.0
      chart: traefik
      helm:
        skipCrds: true
        valueFiles:
          - $values/kubernetes/argocd/stacks/traefik/values.yml
    - path: kubernetes/argocd/stacks/traefik
      repoURL: 'git@github.com:acm-uic/IaC.git'
      targetRevision: HEAD
      ref: values
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
