---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://helm.releases.hashicorp.com'
      # Helm will not update CRDs upon upgrade
      # More info: https://developer.hashicorp.com/vault/tutorials/kubernetes/vault-secrets-operator#install-the-vault-secrets-operator
      targetRevision: 0.4.0
      chart: 'vault-secrets-operator'
      path: 'helm'
      helm:
        valueFiles:
          - $values/kubernetes/argocd/stacks/vault-secrets-operator/values.yml
    - path: kubernetes/argocd/stacks/vault-secrets-operator
      repoURL: 'git@github.com:acm-uic/IaC.git'
      targetRevision: HEAD
      ref: values
      directory:
        recurse: true
        include: '*.yml'
        exclude: values.yml
  project: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

