name: labels

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labels.yml"

jobs:
  labeler:
    runs-on: acmapp-k8s
    container:
      image: ghcr.io/actions/actions-runner:latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3
      - name: Run Labeler 🏷
        uses: crazy-max/ghaction-github-labeler@v4
